name: Release Project
on: workflow_dispatch
  
jobs:

  Task03_ReleaseProject:

    runs-on: windows-latest 
    
    permissions: write-all
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 6.0.x  
    - name: Make Package
      run: dotnet pack
      working-directory: PowerCollections    
    - name: Publish Package
      run: dotnet nuget push "PowerCollections\bin\Debug\*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/DimiDondon/index.json --skip-duplicate
      working-directory: PowerCollections
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with: 
        xml-file: 'PowerCollections/PowerCollections/PowerCollections.csproj'
        xpath: '//Version'
    - name: Make Release 
      uses: ncipollo/release-action@v1.12.0
      with: 
        tag: 'v${{ steps.getxml.outputs.info }}'
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'

